services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    env_file:
      - path: ./.env
        
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: